-- A tiny Haskell module that exports a function for the RTS linker
-- to resolve, invoke, and return a result from.  Tests the PPC
-- Mach-O loader with relocs only generated by Haskell object code:
-- info-table refs, static closures, cross-section HI16/LO16/HA16
-- halves, _SECTDIFF pairs.
module Greeter (haskellGreet, haskellAnswer) where

import Foreign.C.String
import Foreign.C.Types

foreign import ccall "puts" c_puts :: CString -> IO CInt

haskellGreet :: IO ()
haskellGreet = do
  _ <- withCString "relocateSectionPPC: hello from a loaded Haskell .o!" c_puts
  return ()

haskellAnswer :: CInt
haskellAnswer = 9001
