#!/opt/tigersh-deps-0.1/bin/bash
# Install the GHC 7.0.4 binary framework on Tiger.
#
# Prereqs:
#   * /opt/libiconv-1.16/lib/libiconv.2.dylib present (via tiger.sh)
#   * /Library/Frameworks exists
#   * /Library/Frameworks/GHC.framework.tar has been rsync'd to /tmp/
#
# Strategy: extract the framework, then write wrapper scripts in
# /usr/local/bin/ that set DYLD_FALLBACK_LIBRARY_PATH=/opt/libiconv-1.16/lib.
# This bypasses the libiconv ABI mismatch without requiring
# install_name_tool surgery on the PPC binaries (modern
# install_name_tool on Apple Silicon can't rewrite PPC Mach-O).
#
# Can be safely re-run (idempotent).

set -e -o pipefail

PKG_TAR="${PKG_TAR:-/tmp/ghc-7.0.4-framework.tar}"
FRAMEWORK_DIR="/Library/Frameworks/GHC.framework"
VERSION="7.0.4-powerpc"
VERS_DIR="$FRAMEWORK_DIR/Versions/$VERSION"
LIBICONV="/opt/libiconv-1.16/lib"
BINDIR="/usr/local/bin"

echo "== GHC 7.0.4 install on $(sw_vers -productVersion) / $(uname -p)"

if [ ! -f "$PKG_TAR" ]; then
    echo "ERROR: $PKG_TAR missing.  rsync it first from the main Mac."
    exit 1
fi

if [ ! -d "$LIBICONV" ]; then
    echo "ERROR: $LIBICONV missing.  Install libiconv-1.16 via tiger.sh."
    exit 1
fi

if [ ! -d /Library/Frameworks ]; then
    sudo mkdir -p /Library/Frameworks
fi

echo "-- extracting framework"
if [ -d "$VERS_DIR" ]; then
    echo "   (already present at $VERS_DIR; skipping extract)"
else
    sudo tar -C /Library/Frameworks -xf "$PKG_TAR"
fi

ls -la "$VERS_DIR/usr/bin/" | head -5

echo "-- writing wrapper scripts into $BINDIR"
sudo mkdir -p "$BINDIR"

for name in ghc ghci ghc-pkg runghc runhaskell hsc2hs haddock hpc hp2ps; do
    TARGET="$VERS_DIR/usr/bin/$name"
    if [ ! -e "$TARGET" ]; then
        continue
    fi

    WRAPPER="$BINDIR/$name-7.0.4"
    sudo tee "$WRAPPER" > /dev/null <<WRAPPER_EOF
#!/bin/sh
# Auto-generated by install-ghc-704-on-tiger.sh
#
# Sets DYLD_LIBRARY_PATH to pick up /opt/libiconv-1.16/lib's
# libiconv.2.dylib (compat 7.0.0), which is newer than Tiger's
# /usr/lib/libiconv.2.dylib (compat 5.0.0) that the prebuilt GHC
# 7.0.4 binary requires.
#
# Note: DYLD_FALLBACK_LIBRARY_PATH does NOT work here because dyld
# only consults FALLBACK when the original path is missing.  The
# original path exists on Tiger, just with an incompatible compat
# version, so dyld errors out before the fallback kicks in.
# DYLD_LIBRARY_PATH is consulted *before* the install name's path,
# so it does intercept the lookup.
DYLD_LIBRARY_PATH="$LIBICONV\${DYLD_LIBRARY_PATH:+:\$DYLD_LIBRARY_PATH}"
export DYLD_LIBRARY_PATH
exec "$TARGET" "\$@"
WRAPPER_EOF
    sudo chmod +x "$WRAPPER"
    echo "   wrote $WRAPPER"
done

echo "-- ghc-7.0.4 --version:"
ghc-7.0.4 --version || {
    echo "ERROR: ghc-7.0.4 failed to run.  See DYLD_FALLBACK_LIBRARY_PATH workaround in"
    echo "       ~/claude/ghc-darwin8-ppc/docs/notes/iconv-abi-mismatch.md"
    exit 2
}

echo "-- smoke test: hello world"
TMPDIR="${TMPDIR:-/tmp}/ghc-smoke-$$"
mkdir -p "$TMPDIR"
trap 'rm -rf "$TMPDIR"' EXIT

cat > "$TMPDIR/hello.hs" <<'EOF'
main = putStrLn "hello from ghc-7.0.4 on Tiger"
EOF

(cd "$TMPDIR" && ghc-7.0.4 -o hello hello.hs 2>&1 | tail -5)
if [ -x "$TMPDIR/hello" ]; then
    echo "-- file hello:"
    file "$TMPDIR/hello"
    echo "-- output:"
    "$TMPDIR/hello"
else
    echo "ERROR: compile failed"
    exit 3
fi

echo "== install-ghc-704-on-tiger.sh: OK"
